### ISSUE TITLE
File a vendor review for Mail Chimp

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1345]
Mail Chimp has not been through a Mozilla vendor security review. Need to do this before the Thunderbird team considers using it. I will file the bug since I'm not sure @rkent has access.

Bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1250726 

Flagging that this may become a blocker to the overall project.

cc @davidascher

**Comment by rkent** [comment]
Please cc me on that bug.


On February 23, 2016 4:33:34 PM PST, Erika Drushka <notifications@github.com> wrote:
>Mail Chimp has not been through a Mozilla vendor security review. Need
>to do this before the Thunderbird team considers using it. I will file
>the bug since I'm not sure @rkent has access.
>
>Bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1250726 
>
>Flagging that this may become a blocker to the overall project.
>
>cc @davidascher 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/donate.mozilla.org/issues/1345

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edrushka** [comment]
Done. Let me know if you can't access it.

**Comment by rkent** [comment]
No I still cannot see it. Can you confirm that rkent@caspia.com is the 
account that is cc'd?

**Comment by edrushka** [comment]
Try now. I might have done a bad copy/paste.

**Comment by rkent** [comment]
Yes that worked. Thanks.

**Comment by edrushka** [comment]
On second thought, this will not block the overall project. The TB team can still accept donations. They simply may not be able to email the list right away (using Mailchimp, anyways).

**Comment by rkent** [comment]
If there is anything else that is blocking the project that is waiting 
on me, please ping me. I really want this to move forward.

**Comment by edrushka** [comment]
Nope, no blockers at this time @rkent. And in fact, the dev and designer are working on this right this minute :) I hope to post their mockup in the next couple days. Link on staging should hopefully follow shortly after.

**Comment by ScottDowne** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1250726

No need to track this here too.
